import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 10, fontFamily: "Helvetica", color: "#1F2937" },
  title: { fontSize: 18, color: "#16A34A", marginBottom: 8, fontWeight: "bold" },
  table: { marginTop: 12, borderWidth: 1, borderColor: "#D1D5DB" },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#D1D5DB" },
  cell: { padding: 6, borderRightWidth: 1, borderRightColor: "#D1D5DB" },
  headerCell: { backgroundColor: "#ECFDF5", fontWeight: "bold" }
});

export function ReservationsSummaryDoc({
  title,
  rows
}: {
  title: string;
  rows: Array<{ id: number; name: string; item: string; status: string; date: string }>;
}) {
  return (
    <Document title={title}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text>Generated by Barangay Facility and Equipment Management System</Text>
        <View style={styles.table}>
          <View style={styles.row}>
            {["ID", "Name", "Item", "Status", "Date"].map((h) => (
              <Text key={h} style={[styles.cell, styles.headerCell, { width: h === "Item" ? "30%" : "17.5%" }]}>{h}</Text>
            ))}
          </View>
          {rows.map((row) => (
            <View key={row.id} style={styles.row}>
              <Text style={[styles.cell, { width: "17.5%" }]}>{row.id}</Text>
              <Text style={[styles.cell, { width: "17.5%" }]}>{row.name}</Text>
              <Text style={[styles.cell, { width: "30%" }]}>{row.item}</Text>
              <Text style={[styles.cell, { width: "17.5%" }]}>{row.status}</Text>
              <Text style={[styles.cell, { width: "17.5%", borderRightWidth: 0 }]}>{row.date}</Text>
            </View>
          ))}
        </View>
      </Page>
    </Document>
  );
}
