SET search_path = public;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'facility_status_enum'
  ) THEN
    CREATE TYPE public.facility_status_enum AS ENUM ('AVAILABLE', 'UNDER_MAINTENANCE');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'reservation_status_enum'
  ) THEN
    CREATE TYPE public.reservation_status_enum AS ENUM ('PENDING', 'APPROVED', 'DENIED', 'CANCELLED');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'equipment_return_status_enum'
  ) THEN
    CREATE TYPE public.equipment_return_status_enum AS ENUM ('BORROWED', 'RETURNED');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'role_enum'
  ) THEN
    CREATE TYPE public.role_enum AS ENUM ('USER', 'ADMIN');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace AND typname = 'admin_role_enum'
  ) THEN
    CREATE TYPE public.admin_role_enum AS ENUM ('CORE_ADMIN', 'ADMIN');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public."Admin" (
  "Admin_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(191) NOT NULL,
  "Birthdate" date,
  "Gender" varchar(50) NOT NULL,
  "Address" varchar(191),
  "Username" varchar(191) NOT NULL,
  "Password" varchar(191) NOT NULL,
  "Contact number" varchar(50) NOT NULL,
  "email" varchar(191) NOT NULL,
  "Role" public.admin_role_enum NOT NULL DEFAULT 'ADMIN',
  "Is_Active" boolean NOT NULL DEFAULT true,
  "CreatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DeactivatedAt" timestamp(3)
);

CREATE TABLE IF NOT EXISTS public."User" (
  "User_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(191) NOT NULL,
  "Birthdate" date,
  "Gender" varchar(50) NOT NULL,
  "Address" varchar(191),
  "Username" varchar(191) NOT NULL,
  "Password" varchar(191) NOT NULL,
  "Contact number" varchar(50) NOT NULL,
  "email" varchar(191) NOT NULL,
  "Role" public.role_enum NOT NULL DEFAULT 'USER',
  "Is_Active" boolean NOT NULL DEFAULT true,
  "DeactivatedAt" timestamp(3)
);

CREATE TABLE IF NOT EXISTS public."Equipment" (
  "Equipment_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Admin_ID" integer NOT NULL,
  "Item_Name" varchar(191) NOT NULL,
  "Description" varchar(191),
  "Price" numeric(65,30),
  "Quantity" integer
);

CREATE TABLE IF NOT EXISTS public."Facility" (
  "Facility_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Admin_ID" integer NOT NULL,
  "Item Name" varchar(191) NOT NULL,
  "Desciption" varchar(191),
  "Status" public.facility_status_enum NOT NULL DEFAULT 'AVAILABLE',
  "Priceperday" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Reservation" (
  "Reservation_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_ID" integer NOT NULL,
  "Equipment_ID" integer,
  "Admin_ID" integer,
  "Facility_ID" integer,
  "Start_DateTime" timestamp(3) NOT NULL,
  "End_DateTime" timestamp(3) NOT NULL,
  "Purpose" varchar(191) NOT NULL,
  "Status" public.reservation_status_enum NOT NULL DEFAULT 'PENDING',
  "Expected_Attendees" integer,
  "Equipment_Quantity" integer,
  "ApprovedAt" timestamp(3),
  "ReturnedAt" timestamp(3),
  "CancelledAt" timestamp(3),
  "Return_Status" public.equipment_return_status_enum,
  "Admin_Notes" varchar(191)
);

CREATE TABLE IF NOT EXISTS public."AppSession" (
  "Session_ID" varchar(191) PRIMARY KEY,
  "Role" public.role_enum NOT NULL,
  "Username" varchar(191) NOT NULL,
  "User_ID" integer,
  "Admin_ID" integer,
  "CreatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "LastActivity" timestamp(3) NOT NULL,
  "ExpiresAt" timestamp(3) NOT NULL,
  "IP_Address" varchar(191),
  "User_Agent" varchar(191)
);

CREATE UNIQUE INDEX IF NOT EXISTS "Admin_Username_key"
  ON public."Admin" ("Username");

CREATE UNIQUE INDEX IF NOT EXISTS "User_Username_key"
  ON public."User" ("Username");

CREATE UNIQUE INDEX IF NOT EXISTS "Reservation_user_facility_start_end_key"
  ON public."Reservation" ("User_ID", "Facility_ID", "Start_DateTime", "End_DateTime");

CREATE UNIQUE INDEX IF NOT EXISTS "Reservation_user_equipment_start_end_key"
  ON public."Reservation" ("User_ID", "Equipment_ID", "Start_DateTime", "End_DateTime");

CREATE INDEX IF NOT EXISTS "Equipment_Admin_ID_idx"
  ON public."Equipment" ("Admin_ID");

CREATE INDEX IF NOT EXISTS "Facility_Admin_ID_idx"
  ON public."Facility" ("Admin_ID");

CREATE INDEX IF NOT EXISTS "Reservation_User_ID_idx"
  ON public."Reservation" ("User_ID");

CREATE INDEX IF NOT EXISTS "Reservation_Equipment_ID_idx"
  ON public."Reservation" ("Equipment_ID");

CREATE INDEX IF NOT EXISTS "Reservation_Admin_ID_idx"
  ON public."Reservation" ("Admin_ID");

CREATE INDEX IF NOT EXISTS "Reservation_Facility_ID_idx"
  ON public."Reservation" ("Facility_ID");

CREATE INDEX IF NOT EXISTS "AppSession_ExpiresAt_idx"
  ON public."AppSession" ("ExpiresAt");

CREATE INDEX IF NOT EXISTS "AppSession_Username_idx"
  ON public."AppSession" ("Username");

CREATE INDEX IF NOT EXISTS "AppSession_Role_User_ID_idx"
  ON public."AppSession" ("Role", "User_ID");

CREATE INDEX IF NOT EXISTS "AppSession_Role_Admin_ID_idx"
  ON public."AppSession" ("Role", "Admin_ID");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Equipment_Admin_ID_fkey'
  ) THEN
    ALTER TABLE public."Equipment"
      ADD CONSTRAINT "Equipment_Admin_ID_fkey"
      FOREIGN KEY ("Admin_ID")
      REFERENCES public."Admin" ("Admin_ID")
      ON DELETE RESTRICT
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Facility_Admin_ID_fkey'
  ) THEN
    ALTER TABLE public."Facility"
      ADD CONSTRAINT "Facility_Admin_ID_fkey"
      FOREIGN KEY ("Admin_ID")
      REFERENCES public."Admin" ("Admin_ID")
      ON DELETE RESTRICT
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Reservation_User_ID_fkey'
  ) THEN
    ALTER TABLE public."Reservation"
      ADD CONSTRAINT "Reservation_User_ID_fkey"
      FOREIGN KEY ("User_ID")
      REFERENCES public."User" ("User_ID")
      ON DELETE RESTRICT
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Reservation_Equipment_ID_fkey'
  ) THEN
    ALTER TABLE public."Reservation"
      ADD CONSTRAINT "Reservation_Equipment_ID_fkey"
      FOREIGN KEY ("Equipment_ID")
      REFERENCES public."Equipment" ("Equipment_ID")
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Reservation_Admin_ID_fkey'
  ) THEN
    ALTER TABLE public."Reservation"
      ADD CONSTRAINT "Reservation_Admin_ID_fkey"
      FOREIGN KEY ("Admin_ID")
      REFERENCES public."Admin" ("Admin_ID")
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Reservation_Facility_ID_fkey'
  ) THEN
    ALTER TABLE public."Reservation"
      ADD CONSTRAINT "Reservation_Facility_ID_fkey"
      FOREIGN KEY ("Facility_ID")
      REFERENCES public."Facility" ("Facility_ID")
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'AppSession_User_ID_fkey'
  ) THEN
    ALTER TABLE public."AppSession"
      ADD CONSTRAINT "AppSession_User_ID_fkey"
      FOREIGN KEY ("User_ID")
      REFERENCES public."User" ("User_ID")
      ON DELETE CASCADE
      ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'AppSession_Admin_ID_fkey'
  ) THEN
    ALTER TABLE public."AppSession"
      ADD CONSTRAINT "AppSession_Admin_ID_fkey"
      FOREIGN KEY ("Admin_ID")
      REFERENCES public."Admin" ("Admin_ID")
      ON DELETE CASCADE
      ON UPDATE CASCADE;
  END IF;
END
$$;
